-- db/init/001-schema.sql
-- Recaptured from Hibernate 7.4.1 / PostgreSQL 17.11 against the Chapter 12
-- Order, LineItem, and UserAccount mappings (PhysicalNamingStrategyStandardImpl).
-- The PostgreSQL image runs this script only when the named volume is empty.

CREATE TABLE public.user_accounts (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT user_accounts_role_check CHECK (((role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'ADMIN'::character varying])::text[])))
);

ALTER TABLE public.user_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.orders (
    order_date date NOT NULL,
    total_price numeric(38,2) NOT NULL,
    created_timestamp timestamp(6) with time zone,
    id bigint NOT NULL,
    updated_timestamp timestamp(6) with time zone,
    user_account_id bigint NOT NULL,
    created_by character varying(255),
    customer_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    updated_by character varying(255)
);

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.lineitem (
    price numeric(38,2),
    quantity integer NOT NULL,
    created_timestamp timestamp(6) with time zone,
    id bigint NOT NULL,
    order_id bigint,
    updated_timestamp timestamp(6) with time zone,
    created_by character varying(255),
    product_name character varying(255),
    updated_by character varying(255)
);

ALTER TABLE public.lineitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lineitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.user_accounts
    ADD CONSTRAINT user_accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_accounts
    ADD CONSTRAINT user_accounts_username_key UNIQUE (username);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.lineitem
    ADD CONSTRAINT lineitem_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkpfjg5h0nctstg1j21b5do5mya FOREIGN KEY (user_account_id) REFERENCES public.user_accounts(id);

ALTER TABLE ONLY public.lineitem
    ADD CONSTRAINT fk6jhw3qeewupya07myovroetaa FOREIGN KEY (order_id) REFERENCES public.orders(id);

CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO public.user_accounts (username, password, role) VALUES
    ('customer@ekart.com', crypt('password123', gen_salt('bf', 10)), 'CUSTOMER'),
    ('othercustomer@ekart.com', crypt('password123', gen_salt('bf', 10)), 'CUSTOMER'),
    ('admin@ekart.com', crypt('password123', gen_salt('bf', 10)), 'ADMIN');
