spring:
  application:
    name: ekart
  profiles:
    default: dev
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  port: 9090
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,conditions,beans,env,mappings
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    org.springframework.boot.autoconfigure.condition: DEBUG
